runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT run:app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /favicon\.ico
  static_files: dist/static/img/favicon.ico
  upload: dist/static/img/favicon\.ico
